import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Booth from './Booth'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ticket Booth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Ticket Booth
        </h1>
        <Booth />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
